blank_issues_enabled: false

contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/wistant
    about: Questions, help, discussions & games
  - name: 📖 Documentation
    url: https://wistant.me
    about: Consult the result

  - name: 🔒 Security Vulnerability
    url: mailto:contact@wistant.me
    about: Security vulnerability — DO NOT open a public issue
